const translations = {
    es: {
        meta_title: "Markiito Valdes",
        lbl_idioma: "IDIOMA",
        alt_hero_img: "Tonah El Hombre Orquesta",
        lbl_edition: "PERCUCIONISTA",
        lbl_hero_title: "MARKITO VALDES",
        btn_conoceme: "CONOCEME",
        btn_portafolio: "PORTAFOLIO DE IMAGENES",
        btn_poder_musica: "MIS SERVICIOS",
        btn_contacto: "REDES SOCIALES",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "CLIC PARA REPRODUCIR",
        btn_grandes_momentos: "GRANDES MOMENTOS",
        modal_grandes_momentos_title: "GRANDES MOMENTOS",
        modal_grandes_momentos_desc: "Toca una imagen para ampliarla y deslizarla",
        btn_cerrar: "Cerrar",
        btn_comparte_historia: "COMPARTIR",
        lbl_producido_por: "PRODUCIDO POR \"TALENT CARD\"",
        btn_contactanos_card: "CONTÁCTANOS",
        lbl_conoceme: "CONOCEME",
        lbl_biografia: "Biografía",
        lbl_hero_title: "MARKIITO VALDÉS",
        lbl_edition: "Percusionista Internacional",
        lbl_nombre_label: "Nombre:",
        val_nombre: "Markiito Valdés",
        lbl_edad_label: "Enfoque:",
        val_edad: "Maestría Rítmica y Escénica",
        lbl_nacimiento_label: "Origen:",
        val_nacimiento: "Morelia, Michoacán",
        lbl_nacionalidad_label: "Nacionalidad:",
        val_nacionalidad: "Mexicana",
        lbl_estatura_label: "Estilo / Rango:",
        val_estatura: "Percusión Global y Latina",
        lbl_formacion_titulo: "Formación Profesional",
        lbl_perfil_label: "Perfil:",
        val_perfil_text: "Destacado Percusionista Mexicano de proyección internacional, originario de Morelia, con una sólida carrera en los escenarios más exigentes.",
        lbl_desempeno_label: "Desempeño:",
        val_desempeno_text: "Virtuosismo, precisión rítmica y una energía desbordante capaz de conectar profundamente con audiencias de todo el mundo.",
        lbl_especialidad_titulo: "Especialidad",
        lbl_disciplina_label: "Disciplina:",
        val_disciplina_text: "Dominio avanzado de percusiones menores y mayores, ensambles latinos y ejecución en giras internacionales.",
        lbl_tecnica_label: "Técnica:",
        val_tecnica_text: "Fusión de ritmos tradicionales y contemporáneos, caracterizada por la pulcritud en el golpe, el tiempo perfecto y la pasión desatada en cada actuación.",
        lbl_logros_titulo: "Logros y Trayectoria",
        val_logro_1: "📌 Embajador del ritmo y la cultura mexicana, llevando el talento de Morelia a escenarios internacionales de gran prestigio musical.",
        val_logro_2: "🌍 Colaboraciones estelares y participaciones al lado de reconocidos exponentes de la industria, imprimiendo su sello único en producciones discográficas y giras globales.",
        val_logro_3: "❤️ Músico ejemplar y ser humano excepcional, reconocido por su generosidad artística, su humildad en el éxito y su compromiso inquebrantable con la excelencia y la pasión por el arte.",
        btn_regresar_menu: "REGRESAR AL MENÚ 🚀",
        contact_title: "REDES SOCIALES",
        contact_contracting: "Redes sociales",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "ESCANEA EL CÓDIGO QR",
        btn_share_qr: "COMPARTIR QR",
        // Nuevos textos agregados desde script.js
        cat2_t: "PORTAFOLIO DE IMAGENES",
        cat2_c: "Pasión, técnica y entrega total para llevar el sonido de México a lo más alto.",
        cat3_t: "MIS SERVICIOS",
        cat3_c: "Sesiones de estudio con precisión rítmica para proyectos discográficos y ejecución en vivo de alto nivel para giras y conciertos con agrupaciones y artistas internacionales.",
        lbl_mis_fortalezas: "México en el corazón",
        btn_tributo_tri: "Experimentando en Casa",
        btn_junto_mar: "En el soundcheck",
        btn_con_gente: "Siempre agradecido",
        btn_ver_detalles: "VER DETALLES"
    },
    en: {
        meta_title: "Markiito Valdes",
        lbl_idioma: "LANGUAGE",
        alt_hero_img: "Tonah The One-Man Band",
        lbl_edition: "PERCUSSIONIST",
        lbl_hero_title: "MARKITO VALDES",
        btn_conoceme: "ABOUT ME",
        btn_portafolio: "IMAGE PORTFOLIO",
        btn_poder_musica: "MY SERVICES",
        btn_contacto: "SOCIAL MEDIA",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "CLICK TO PLAY",
        btn_grandes_momentos: "GREAT MOMENTS",
        modal_grandes_momentos_title: "GREAT MOMENTS",
        modal_grandes_momentos_desc: "Tap an image to zoom and swipe",
        btn_cerrar: "Close",
        btn_comparte_historia: "SHARE",
        lbl_producido_por: "PRODUCED BY \"TALENT CARD\"",
        btn_contactanos_card: "CONTACT US",
        lbl_conoceme: "ABOUT ME",
        lbl_biografia: "Biography",
        lbl_hero_title: "MARKIITO VALDÉS",
        lbl_edition: "International Percussionist",
        lbl_nombre_label: "Name:",
        val_nombre: "Markiito Valdés",
        lbl_edad_label: "Focus:",
        val_edad: "Rhythmic & Stage Mastery",
        lbl_nacimiento_label: "Origin:",
        val_nacimiento: "Morelia, Michoacan",
        lbl_nacionalidad_label: "Nationality:",
        val_nacionalidad: "Mexican",
        lbl_estatura_label: "Style / Range:",
        val_estatura: "Global & Latin Percussion",
        lbl_formacion_titulo: "Professional Background",
        lbl_perfil_label: "Profile:",
        val_perfil_text: "Outstanding Mexican percussionist with international projection, originally from Morelia, with a solid career on the most demanding stages.",
        lbl_desempeno_label: "Performance:",
        val_desempeno_text: "Virtuosity, rhythmic precision, and overwhelming energy capable of deeply connecting with audiences worldwide.",
        lbl_especialidad_titulo: "Specialty",
        lbl_disciplina_label: "Discipline:",
        val_disciplina_text: "Advanced mastery of minor and major percussion, Latin ensembles, and international tour performance.",
        lbl_tecnica_label: "Technique:",
        val_tecnica_text: "Fusion of traditional and contemporary rhythms, characterized by clean striking, perfect timing, and unbridled passion in every performance.",
        lbl_logros_titulo: "Achievements & Career",
        val_logro_1: "📌 Ambassador of rhythm and Mexican culture, taking the talent of Morelia to international stages of great musical prestige.",
        val_logro_2: "🌍 Star collaborations and participations alongside renowned industry exponents, leaving his unique stamp on records and global tours.",
        val_logro_3: "❤️ Exemplary musician and exceptional human being, recognized for his artistic generosity, humility in success, and unwavering commitment to excellence.",
        btn_regresar_menu: "BACK TO MENU 🚀",
        contact_title: "SOCIAL MEDIA",
        contact_contracting: "Social media",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "SCAN THE QR CODE",
        btn_share_qr: "SHARE QR",
        // Nuevos textos agregados desde script.js
        cat2_t: "IMAGE PORTFOLIO",
        cat2_c: "Passion, technique, and total dedication to take the sound of Mexico to the highest level.",
        cat3_t: "MY SERVICES",
        cat3_c: "Studio sessions with rhythmic precision for recording projects and high-level live execution for tours and concerts with international groups and artists.",
        lbl_mis_fortalezas: "Mexico in the Heart",
        btn_tributo_tri: "Experimenting at Home",
        btn_junto_mar: "At the Soundcheck",
        btn_con_gente: "Always Grateful",
        btn_ver_detalles: "VIEW DETAILS"
    },
    pt: {
        meta_title: "Markiito Valdes",
        lbl_idioma: "IDIOMA",
        alt_hero_img: "Tonah O Homem Orquestra",
        lbl_edition: "PERCUSSIONISTA",
        lbl_hero_title: "MARKITO VALDES",
        btn_conoceme: "CONHEÇA-ME",
        btn_portafolio: "PORTFÓLIO DE IMAGENS",
        btn_poder_musica: "MEUS SERVIÇOS",
        btn_contacto: "REDES SOCIAIS",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "CLIQUE PARA REPRODUZIR",
        btn_grandes_momentos: "GRANDES MOMENTOS",
        modal_grandes_momentos_title: "GRANDES MOMENTOS",
        modal_grandes_momentos_desc: "Toque em uma imagem para ampliar e deslizar",
        btn_cerrar: "Fechar",
        btn_comparte_historia: "COMPARTILHAR",
        lbl_producido_por: "PRODUZIDO POR \"TALENT CARD\"",
        btn_contactanos_card: "CONTATE-NOS",
        lbl_conoceme: "CONHEÇA-ME",
        lbl_biografia: "Biografia",
        lbl_hero_title: "MARKIITO VALDÉS",
        lbl_edition: "Percussionista Internacional",
        lbl_nombre_label: "Nome:",
        val_nombre: "Markiito Valdés",
        lbl_edad_label: "Foco:",
        val_edad: "Maestria Rítmica e Cênica",
        lbl_nacimiento_label: "Origem:",
        val_nacimiento: "Morelia, Michoacán",
        lbl_nacionalidad_label: "Nacionalidade:",
        val_nacionalidad: "Mexicana",
        lbl_estatura_label: "Estilo / Alcance:",
        val_estatura: "Percussão Global e Latina",
        lbl_formacion_titulo: "Formação Profissional",
        lbl_perfil_label: "Perfil:",
        val_perfil_text: "Destaque percussionista mexicano de projeção internacional, originário de Morelia, com sólida carreira nos palcos mais exigentes.",
        lbl_desempeno_label: "Desempenho:",
        val_desempeno_text: "Virtuosismo, precisão rítmica e energia transbordante capaz de se conectar profundamente com públicos de todo o mundo.",
        lbl_especialidad_titulo: "Especialidade",
        lbl_disciplina_label: "Disciplina:",
        val_disciplina_text: "Domínio avançado de percussão menor e maior, ensembles latinos e execução em turnês internacionais.",
        lbl_tecnica_label: "Técnica:",
        val_tecnica_text: "Fusão de ritmos tradicionais e contemporâneos, caracterizada pela limpeza na batida, tempo perfeito e paixão desenfreada em cada atuação.",
        lbl_logros_titulo: "Conquistas e Trajetória",
        val_logro_1: "📌 Embaixador do ritmo e da cultura mexicana, levando o talento de Morelia para palcos internacionais de grande prestígio musical.",
        val_logro_2: "🌍 Colaborações estelares e participações ao lado de renomados expoentes da indústria, imprimindo sua marca única em gravações e turnês globais.",
        val_logro_3: "❤️ Músico exemplar e ser humano excepcional, reconhecido por sua generosidade artística, humildade no sucesso e compromisso inabalável com a excelência.",
        btn_regresar_menu: "VOLTAR AO MENU 🚀",
        contact_title: "REDES SOCIAIS",
        contact_contracting: "Redes sociais",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "ESCANEIE O CÓDIGO QR",
        btn_share_qr: "COMPARTILHAR QR",
        // Nuevos textos agregados desde script.js
        cat2_t: "PORTFÓLIO DE IMAGENS",
        cat2_c: "Paixão, técnica e entrega total para levar o som do México ao mais alto patamar.",
        cat3_t: "MEUS SERVIÇOS",
        cat3_c: "Sessões de estúdio com precisão rítmica para projetos discográficos e execução ao vivo de alto nível para turnês e concertos com grupos e artistas internacionais.",
        lbl_mis_fortalezas: "México no Coração",
        btn_tributo_tri: "Experimentando em Casa",
        btn_junto_mar: "No soundcheck",
        btn_con_gente: "Sempre Grato",
        btn_ver_detalles: "VER DETALHES"
    },
    fr: {
        meta_title: "Markiito Valdes",
        lbl_idioma: "LANGUE",
        alt_hero_img: "Tonah L'Homme-Orchestre",
        lbl_edition: "PERCUSSIONNISTE",
        lbl_hero_title: "MARKITO VALDES",
        btn_conoceme: "À PROPOS",
        btn_portafolio: "PORTEFEUILLE D'IMAGES",
        btn_poder_musica: "MES SERVICES",
        btn_contacto: "RÉSEAUX SOCIAUX",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "CLIQUEZ POUR LIRE",
        btn_grandes_momentos: "GRANDS MOMENTS",
        modal_grandes_momentos_title: "GRANDS MOMENTS",
        modal_grandes_momentos_desc: "Touchez une image pour l'agrandir et balayer",
        btn_cerrar: "Fermer",
        btn_comparte_historia: "PARTAGER",
        lbl_producido_por: "PRODUIT PAR \"TALENT CARD\"",
        btn_contactanos_card: "CONTACTEZ-NOUS",
        lbl_conoceme: "À PROPOS",
        lbl_biografia: "Biographie",
        lbl_hero_title: "MARKIITO VALDÉS",
        lbl_edition: "Percussionniste International",
        lbl_nombre_label: "Nom :",
        val_nombre: "Markiito Valdés",
        lbl_edad_label: "Approche :",
        val_edad: "Maîtrise Rythmique et Scénique",
        lbl_nacimiento_label: "Origine :",
        val_nacimiento: "Morelia, Michoacán",
        lbl_nacionalidad_label: "Nationalité :",
        val_nacionalidad: "Mexicaine",
        lbl_estatura_label: "Style / Gamme :",
        val_estatura: "Percussion Globale et Latine",
        lbl_formacion_titulo: "Parcours Professionnel",
        lbl_perfil_label: "Profil :",
        val_perfil_text: "Éminent percussionniste mexicain à projection internationale, originaire de Morelia, avec une solide carrière sur les scènes les plus exigeantes.",
        lbl_desempeno_label: "Performance :",
        val_desempeno_text: "Virtuosité, précision rythmique et énergie débordante capable de se connecter profondément avec des publics du monde entier.",
        lbl_especialidad_titulo: "Spécialité",
        lbl_disciplina_label: "Discipline :",
        val_disciplina_text: "Maîtrise avancée des percussions mineures et majeures, ensembles latins et exécution en tournées internationales.",
        lbl_tecnica_label: "Technique :",
        val_tecnica_text: "Fusion de rythmes traditionnels et contemporains, caractérisée par la propreté du coup, le tempo parfait et la passion déchaînée à chaque prestation.",
        lbl_logros_titulo: "Réalisations et Carrière",
        val_logro_1: "📌 Ambassadeur du rythme et de la culture mexicaine, portant le talent de Morelia sur des scènes internationales de grand prestige musical.",
        val_logro_2: "🌍 Collaborations stellaires et participations aux côtés d'exposants renommés de l'industrie, imprimant sa marque unique dans des disques et tournées mondiales.",
        val_logro_3: "❤️ Musicien exemplaire et être humain exceptionnel, reconnu pour sa générosité artistique, son humilité dans le succès et son engagement inébranlable.",
        btn_regresar_menu: "RETOURNER AU MENU 🚀",
        contact_title: "RÉSEAUX SOCIAUX",
        contact_contracting: "Réseaux sociaux",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "SCANNEZ LE CODE QR",
        btn_share_qr: "PARTAGER QR",
        // Nuevos textos agregados desde script.js
        cat2_t: "PORTEFEUILLE D'IMAGES",
        cat2_c: "Passion, technique et dévouement total pour porter le son du Mexique au plus haut niveau.",
        cat3_t: "MES SERVICES",
        cat3_c: "Séances de studio avec précision rythmique pour projets discographiques et exécution live de haut niveau pour tournées et concerts avec des groupes et artistes internationaux.",
        lbl_mis_fortalezas: "Le Mexique dans le Cœur",
        btn_tributo_tri: "Expérimentation à la Maison",
        btn_junto_mar: "Au Soundcheck",
        btn_con_gente: "Toujours Reconnaissant",
        btn_ver_detalles: "VOIR LES DÉTAILS"
    },
    ko: {
        meta_title: "Markiito Valdes",
        lbl_idioma: "언어",
        alt_hero_img: "토나 원맨밴드",
        lbl_edition: "퍼커션 연주자",
        lbl_hero_title: "MARKITO VALDES",
        btn_conoceme: "소개",
        btn_portafolio: "이미지 포트폴리오",
        btn_poder_musica: "나의 서비스",
        btn_contacto: "소셜 미디어",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "재생하려면 클릭",
        btn_grandes_momentos: "위대한 순간들",
        modal_grandes_momentos_title: "위대한 순간들",
        modal_grandes_momentos_desc: "이미지를 터치하여 확대하고 슬라이드하세요",
        btn_cerrar: "닫기",
        btn_comparte_historia: "공유하기",
        lbl_producido_por: "제작 \"TALENT CARD\"",
        btn_contactanos_card: "문의하기",
        lbl_conoceme: "소개",
        lbl_biografia: "전기",
        lbl_hero_title: "MARKIITO VALDÉS",
        lbl_edition: "국제 타악기 연주자",
        lbl_nombre_label: "이름:",
        val_nombre: "Markiito Valdés",
        lbl_edad_label: "초점:",
        val_edad: "리듬 및 무대 숙달",
        lbl_nacimiento_label: "출신:",
        val_nacimiento: "멕시코 모렐리아",
        lbl_nacionalidad_label: "국적:",
        val_nacionalidad: "멕시코인",
        lbl_estatura_label: "스타일 / 범위:",
        val_estatura: "글로벌 및 라틴 퍼커션",
        lbl_formacion_titulo: "전문 경력",
        lbl_perfil_label: "프로필:",
        val_perfil_text: "모렐리아 출신의 뛰어난 국제적 멕시코 타악기 연주자로, 가장 까다로운 무대에서 탄탄한 경력을 쌓았습니다.",
        lbl_desempeno_label: "공연:",
        val_desempeno_text: "비르투오소, 리듬의 정확성, 그리고 전 세계 관객과 깊이 교감할 수 있는 넘치는 에너지를 지니고 있습니다.",
        lbl_especialidad_titulo: "전문 분야",
        lbl_disciplina_label: "규율:",
        val_disciplina_text: "소형 및 대형 타악기, 라틴 앙상블 및 국제 투어 연주에 대한 고급 숙련도.",
        lbl_tecnica_label: "기술:",
        val_tecnica_text: "전통 리듬과 현대 리듬의 융합으로, 깔끔한 타격, 완벽한 박자, 그리고 모든 공연에서의 거침없는 열정이 특징입니다.",
        lbl_logros_titulo: "업적 및 경력",
        val_logro_1: "📌 리듬과 멕시코 문화의 홍보대사로서 모렐리아의 재능을 음악적 명성이 높은 국제 무대로 이끌고 있습니다.",
        val_logro_2: "🌍 업계 유명 인사들과의 스타 협업 및 참여를 통해 음반과 글로벌 투어에 자신만의 독특한 흔적을 남겼습니다.",
        val_logro_3: "❤️ 예술적 관대함, 성공 속의 겸손함, 우수성에 대한 변함없는 헌신으로 인정받는 모범적인 음악가이자 예외적인 인간입니다.",
        btn_regresar_menu: "메뉴로 돌아가기 🚀",
        contact_title: "소셜 미디어",
        contact_contracting: "소셜 미디어",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "QR 코드 스캔",
        btn_share_qr: "QR 공유",
        // Nuevos textos agregados desde script.js
        cat2_t: "이미지 포트폴리오",
        cat2_c: "멕시코의 사운드를 최고 수준으로 끌어올리기 위한 열정, 기술, 그리고 완벽한 헌신.",
        cat3_t: "나의 서비스",
        cat3_c: "음반 프로젝트를 위한 리듬 정밀도가 담긴 스튜디오 세션과, 국제 그룹 및 아티스트와의 투어/콘서트를 위한 고품격 라이브 연주.",
        lbl_mis_fortalezas: "마음속의 멕시코",
        btn_tributo_tri: "집에서 실험하기",
        btn_junto_mar: "사운드체크 현장에서",
        btn_con_gente: "항상 감사하는 마음",
        btn_ver_detalles: "상세 보기"
    },
    de: {
        meta_title: "Markiito Valdes",
        lbl_idioma: "SPRACHE",
        alt_hero_img: "Tonah Die Ein-Mann-Band",
        lbl_edition: "SCHLAGZEUGER",
        lbl_hero_title: "MARKITO VALDES",
        btn_conoceme: "ÜBER MICH",
        btn_portafolio: "BILDERPORTFOLIO",
        btn_poder_musica: "MEINE DIENSTLEISTUNGEN",
        btn_contacto: "SOZIALE MEDIEN",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "KLICKEN ZUM ABSPIELEN",
        btn_grandes_momentos: "GROSSE MOMENTE",
        modal_grandes_momentos_title: "GROSSE MOMENTE",
        modal_grandes_momentos_desc: "Tippen Sie auf ein Bild, um es zu zoomen und zu wischen",
        btn_cerrar: "Schließen",
        btn_comparte_historia: "TEILEN",
        lbl_producido_por: "PRODUZIERT VON \"TALENT CARD\"",
        btn_contactanos_card: "KONTAKTIEREN SIE UNS",
        lbl_conoceme: "ÜBER MICH",
        lbl_biografia: "Biografie",
        lbl_hero_title: "MARKIITO VALDÉS",
        lbl_edition: "Internationaler Perkussionist",
        lbl_nombre_label: "Name:",
        val_nombre: "Markiito Valdés",
        lbl_edad_label: "Schwerpunkt:",
        val_edad: "Rhythmische & Bühnenmeisterschaft",
        lbl_nacimiento_label: "Herkunft:",
        val_nacimiento: "Morelia, Michoacán",
        lbl_nacionalidad_label: "Nationalität:",
        val_nacionalidad: "Mexikanisch",
        lbl_estatura_label: "Stil / Bereich:",
        val_estatura: "Globale & Lateinamerikanische Perkussion",
        lbl_formacion_titulo: "Beruflicher Werdegang",
        lbl_perfil_label: "Profil:",
        val_perfil_text: "Hervorragender mexikanischer Perkussionist mit internationaler Ausrichtung, stammt aus Morelia und hat eine solide Karriere auf den anspruchsvollsten Bühnen.",
        lbl_desempeno_label: "Leistung:",
        val_desempeno_text: "Virtuosität, rhythmische Präzision und überschäumende Energie, die in der Lage ist, tief mit Publikum weltweit zu verbinden.",
        lbl_especialidad_titulo: "Spezialität",
        lbl_disciplina_label: "Disziplin:",
        val_disciplina_text: "Fortgeschrittene Beherrschung von Klein- und Großperkussion, lateinamerikanischen Ensembles und internationalen Tourneen.",
        lbl_tecnica_label: "Technik:",
        val_tecnica_text: "Verschmelzung traditioneller und zeitgenössischer Rhythmen, gekennzeichnet durch Sauberkeit im Anschlag, perfektes Timing und entfesselte Leidenschaft.",
        lbl_logros_titulo: "Erfolge und Karriere",
        val_logro_1: "📌 Botschafter des Rhythmus und der mexikanischen Kultur, der das Talent von Morelia auf internationale Bühnen von großem Musikprestige bringt.",
        val_logro_2: "🌍 Sternkollaborationen und Teilnahmen an der Seite renommierter Branchenvertreter, die seinen einzigartigen Stempel auf Platten und Welttourneen hinterlassen.",
        val_logro_3: "❤️ Vorbildlicher Musiker und außergewöhnlicher Mensch, anerkannt für seine künstlerische Großzügigkeit, Bescheidenheit im Erfolg und unerschütterliches Engagement.",
        btn_regresar_menu: "ZURÜCK ZUM MENÜ 🚀",
        contact_title: "SOZIALE MEDIEN",
        contact_contracting: "Soziale Medien",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "QR-CODE SCANNEN",
        btn_share_qr: "QR TEILEN",
        // Nuevos textos agregados desde script.js
        cat2_t: "BILDERPORTFOLIO",
        cat2_c: "Leidenschaft, Technik und voller Einsatz, um den Klang Mexikos auf höchstes Niveau zu bringen.",
        cat3_t: "MEINE DIENSTLEISTUNGEN",
        cat3_c: "Studiomitschnitte mit rhythmischer Präzision für Plattenprojekte und erstklassige Live-Performances für Tourneen und Konzerte mit internationalen Künstlern.",
        lbl_mis_fortalezas: "Mexiko im Herzen",
        btn_tributo_tri: "Zu Hause experimentieren",
        btn_junto_mar: "Beim Soundcheck",
        btn_con_gente: "Immer dankbar",
        btn_ver_detalles: "DETAILS ANSEHEN"
    },
    ja: {
        meta_title: "Markiito Valdes",
        lbl_idioma: "言語",
        alt_hero_img: "トナ ワンマンバンド",
        lbl_edition: "パーカッショニスト",
        lbl_hero_title: "MARKITO VALDES",
        btn_conoceme: "私について",
        btn_portafolio: "画像ポートフォリオ",
        btn_poder_musica: "マイサービス",
        btn_contacto: "ソーシャルメディア",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "クリックして再生",
        btn_grandes_momentos: "偉大な瞬間",
        modal_grandes_momentos_title: "偉大な瞬間",
        modal_grandes_momentos_desc: "画像をタップして拡大・スワイプしてください",
        btn_cerrar: "閉じる",
        btn_comparte_historia: "シェア",
        lbl_producido_por: "プロデュース: \"TALENT CARD\"",
        btn_contactanos_card: "お問い合わせ",
        lbl_conoceme: "私について",
        lbl_biografia: "経歴",
        lbl_hero_title: "MARKIITO VALDÉS",
        lbl_edition: "国際的パーカッショニスト",
        lbl_nombre_label: "名前:",
        val_nombre: "Markiito Valdés",
        lbl_edad_label: "フォーカス:",
        val_edad: "リズムとステージの習熟",
        lbl_nacimiento_label: "出身:",
        val_nacimiento: "モレリア、ミチョアカン",
        lbl_nacionalidad_label: "国籍:",
        val_nacionalidad: "メキシコ",
        lbl_estatura_label: "スタイル/範囲:",
        val_estatura: "グローバル＆ラテンパーカッション",
        lbl_formacion_titulo: "経歴・プロフィール",
        lbl_perfil_label: "プロフィール:",
        val_perfil_text: "モレリア出身の国際的な活躍を誇る卓越したメキシコ人パーカッショニスト。最も要求の厳しいステージで確固たるキャリアを築いています。",
        lbl_desempeno_label: "パフォーマンス:",
        val_desempeno_text: "超絶技巧、リズムの正確さ、そして世界中のオーディエンスと深くつながる圧倒的なエネルギーを持っています。",
        lbl_especialidad_titulo: "専門分野",
        lbl_disciplina_label: "分野:",
        val_disciplina_text: "小・大パーカッション、ラテンアンサンブル、国際ツアーにおける高度な演奏技術。",
        lbl_tecnica_label: "テクニック:",
        val_tecnica_text: "伝統と現代のリズムの融合。澄んだ打音、完璧なタイミング、すべての演奏における情熱が特徴です。",
        lbl_logros_titulo: "実績とキャリア",
        val_logro_1: "📌 リズムとメキシコ文化のアンバサダーとして、モレリアの才能を音楽的権威のある国際舞台へと導いています。",
        val_logro_2: "🌍 業界の著名アーティストとのコラボレーションを通じて、アルバムや世界ツアーに独自の足跡を残しています。",
        val_logro_3: "❤️ 芸術的な寛大さ、成功における謙虚さ、そして卓越性への揺るぎないコミットメントで知られる模範的な音楽家です。",
        btn_regresar_menu: "メニューに戻る 🚀",
        contact_title: "ソーシャルメディア",
        contact_contracting: "ソーシャルメディア",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "QRコードをスキャン",
        btn_share_qr: "QR共有",
        // Nuevos textos agregados desde script.js
        cat2_t: "画像ポートフォリオ",
        cat2_c: "メキシコのサウンドを最高峰へ高めるための情熱、テクニック、そして完全な献身。",
        cat3_t: "マイサービス",
        cat3_c: "レコーディングプロジェクト向けのリズムの正確性を持つスタジオセッション、および国際的なアーティストとのツアーやコンサートのためのハイレベルなライブ演奏。",
        lbl_mis_fortalezas: "心の中のメキシコ",
        btn_tributo_tri: "自宅で実験中",
        btn_junto_mar: "サウンドチェックにて",
        btn_con_gente: "いつも感謝",
        btn_ver_detalles: "詳細を見る"
    },
    zh: {
        meta_title: "Markiito Valdes",
        lbl_idioma: "语言",
        alt_hero_img: "Tonah 一人乐队",
        lbl_edition: "打击乐手",
        lbl_hero_title: "MARKITO VALDES",
        btn_conoceme: "关于我",
        btn_portafolio: "图片作品集",
        btn_poder_musica: "我的服务",
        btn_contacto: "社交媒体",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "点击播放",
        btn_grandes_momentos: "精彩瞬间",
        modal_grandes_momentos_title: "精彩瞬间",
        modal_grandes_momentos_desc: "点击图片放大并滑动查看",
        btn_cerrar: "关闭",
        btn_comparte_historia: "分享",
        lbl_producido_por: "制片方：\"TALENT CARD\"",
        btn_contactanos_card: "联系我们",
        lbl_conoceme: "关于我",
        lbl_biografia: "传记",
        lbl_hero_title: "MARKIITO VALDÉS",
        lbl_edition: "国际打击乐手",
        lbl_nombre_label: "姓名：",
        val_nombre: "Markiito Valdés",
        lbl_edad_label: "方向：",
        val_edad: "节奏与舞台掌控",
        lbl_nacimiento_label: "出生地：",
        val_nacimiento: "米却肯州莫雷利亚",
        lbl_nacionalidad_label: "国籍：",
        val_nacionalidad: "墨西哥",
        lbl_estatura_label: "风格/范围：",
        val_estatura: "全球与拉丁打击乐",
        lbl_formacion_titulo: "专业背景",
        lbl_perfil_label: "简介：",
        val_perfil_text: "杰出的墨西哥国际级打击乐手，原籍莫雷利亚，在要求严苛的舞台上拥有扎实的职业生涯。",
        lbl_desempeno_label: "表现：",
        val_desempeno_text: "精湛的技术、精准的节奏以及能够与世界各地观众产生深刻共鸣的压倒性能量。",
        lbl_especialidad_titulo: "专业特长",
        lbl_disciplina_label: "学科：",
        val_disciplina_text: "精通大小打击乐、拉丁乐团及国际巡演演出。",
        lbl_tecnica_label: "技术：",
        val_tecnica_text: "传统与现代节奏的融合，其特点是击打纯净、节拍完美以及每场表演中释放的无限激情。",
        lbl_logros_titulo: "成就与职业生涯",
        val_logro_1: "📌 节奏与墨西哥文化的使者，将莫雷利亚的天赋带到具有高度音乐声誉的国际舞台。",
        val_logro_2: "🌍 与业内知名大咖进行星级合作和参与，在唱片和全球巡演中留下了他独特的印记。",
        val_logro_3: "❤️ 堪称楷模的音乐家和卓越的人，以其艺术慷慨、成功时的谦逊以及对卓越的不懈追求而闻名。",
        btn_regresar_menu: "返回菜单 🚀",
        contact_title: "社交媒体",
        contact_contracting: "社交媒体",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "扫描二维码",
        btn_share_qr: "分享二维码",
        // Nuevos textos agregados desde script.js
        cat2_t: "图片作品集",
        cat2_c: "充满激情、技巧与全心奉献，将墨西哥的声音带向最高峰。",
        cat3_t: "我的服务",
        cat3_c: "具备节奏精准度的录音室专辑制作，以及与国际乐团和知名艺术家合作的高水准现场巡演与音乐会演出。",
        lbl_mis_fortalezas: "墨西哥在心中",
        btn_tributo_tri: "在家中进行实验",
        btn_junto_mar: "在试音现场",
        btn_con_gente: "永远心怀感激",
        btn_ver_detalles: "查看详情"
    }
};

function changeLanguage(lang) {
    localStorage.setItem('selectedLanguage', lang);

    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    const altElements = document.querySelectorAll('[data-i18n-alt]');
    altElements.forEach(el => {
        const key = el.getAttribute('data-i18n-alt');
        if (translations[lang] && translations[lang][key]) {
            el.setAttribute('alt', translations[lang][key]);
        }
    });

    if (translations[lang] && translations[lang]['meta_title']) {
        document.title = translations[lang]['meta_title'];
    }

    document.querySelectorAll('.lang-chip').forEach(chip => {
        chip.classList.remove('active');
        if (chip.getAttribute('onclick') && chip.getAttribute('onclick').includes(`'${lang}'`)) {
            chip.classList.add('active');
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLanguage') || 'es';
    changeLanguage(savedLang);
});